#!/usr/bin/env bash
#===============================================================================
# hard.sh — Bootstrap & execute dev-sec ansible-collection-hardening locally
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/<you>/hard.sh | sudo bash
#   — or —
#   chmod +x hard.sh && sudo ./hard.sh
#
# Options (env vars):
#   HARDEN_OS=true|false      (default: true)  — OS hardening
#   HARDEN_SSH=true|false     (default: true)  — SSH hardening
#   HARDEN_MYSQL=true|false   (default: false) — MySQL hardening
#   HARDEN_NGINX=true|false   (default: false) — Nginx hardening
#   DRY_RUN=true|false        (default: false) — Ansible check mode
#   VERBOSE=true|false        (default: false) — Ansible verbose output
#===============================================================================

set -euo pipefail
IFS=$'\n\t'

# ── Colours & helpers ────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; NC='\033[0m'

log()   { echo -e "${GREEN}[✔]${NC} $*"; }
warn()  { echo -e "${YELLOW}[!]${NC} $*"; }
err()   { echo -e "${RED}[✘]${NC} $*" >&2; }
banner(){ echo -e "\n${CYAN}═══════════════════════════════════════════${NC}"
          echo -e "${CYAN}  $*${NC}"
          echo -e "${CYAN}═══════════════════════════════════════════${NC}\n"; }

# ── Default configuration ───────────────────────────────────────────────────
HARDEN_OS="${HARDEN_OS:-true}"
HARDEN_SSH="${HARDEN_SSH:-true}"
HARDEN_MYSQL="${HARDEN_MYSQL:-false}"
HARDEN_NGINX="${HARDEN_NGINX:-false}"
DRY_RUN="${DRY_RUN:-false}"
VERBOSE="${VERBOSE:-false}"

WORK_DIR="/tmp/hardening-$$"
COLLECTION="devsec.hardening"
COLLECTION_VERSION="${COLLECTION_VERSION:-}"   # empty = latest
PLAYBOOK="${WORK_DIR}/hardening-playbook.yml"
LOGFILE="/var/log/hard-sh-$(date +%Y%m%d-%H%M%S).log"

# ── Pre-flight checks ───────────────────────────────────────────────────────
banner "dev-sec Hardening Bootstrap"

if [[ $EUID -ne 0 ]]; then
    err "This script must be run as root (or with sudo)."
    exit 1
fi

mkdir -p "${WORK_DIR}"
log "Working directory: ${WORK_DIR}"
log "Log file:          ${LOGFILE}"

# ── Detect package manager ──────────────────────────────────────────────────
detect_pkg_manager() {
    if   command -v apt-get &>/dev/null; then echo "apt"
    elif command -v dnf     &>/dev/null; then echo "dnf"
    elif command -v yum     &>/dev/null; then echo "yum"
    elif command -v zypper  &>/dev/null; then echo "zypper"
    elif command -v pacman  &>/dev/null; then echo "pacman"
    else echo "unknown"; fi
}

PKG_MGR=$(detect_pkg_manager)
log "Detected package manager: ${PKG_MGR}"

# ── Install system dependencies ─────────────────────────────────────────────
install_system_deps() {
    banner "Installing system dependencies"

    case "${PKG_MGR}" in
        apt)
            apt-get update -qq
            apt-get install -y -qq python3 python3-pip python3-venv git curl >/dev/null
            ;;
        dnf)
            dnf install -y -q python3 python3-pip git curl
            ;;
        yum)
            yum install -y -q python3 python3-pip git curl
            ;;
        zypper)
            zypper install -y python3 python3-pip git curl
            ;;
        pacman)
            pacman -Sy --noconfirm python python-pip git curl
            ;;
        *)
            err "Unsupported package manager. Install python3, pip, and git manually."
            exit 1
            ;;
    esac

    log "System dependencies installed."
}

# ── Install / upgrade Ansible ───────────────────────────────────────────────
install_ansible() {
    banner "Setting up Ansible"

    # Create a virtual-env so we don't pollute the system Python
    VENV="${WORK_DIR}/venv"
    python3 -m venv "${VENV}"
    # shellcheck source=/dev/null
    source "${VENV}/bin/activate"

    pip install --upgrade pip setuptools wheel -q
    pip install ansible-core ansible -q

    log "Ansible $(ansible --version | head -1) installed in venv."
}

# ── Install the dev-sec collection ──────────────────────────────────────────
install_collection() {
    banner "Installing Ansible collection: ${COLLECTION}"

    local col_spec="${COLLECTION}"
    [[ -n "${COLLECTION_VERSION}" ]] && col_spec="${COLLECTION}:${COLLECTION_VERSION}"

    ansible-galaxy collection install "${col_spec}" --force 2>&1 | tee -a "${LOGFILE}"

    log "Collection ${COLLECTION} installed."
    ansible-galaxy collection list | grep devsec || true
}

# ── Build the playbook dynamically ──────────────────────────────────────────
build_playbook() {
    banner "Building hardening playbook"

    cat > "${PLAYBOOK}" <<HEADER
---
# Auto-generated by hard.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
- name: Apply dev-sec hardening
  hosts: localhost
  connection: local
  become: true

  roles:
HEADER

    if [[ "${HARDEN_OS}" == "true" ]]; then
        echo "    - devsec.hardening.os_hardening" >> "${PLAYBOOK}"
        log "  → OS hardening   ENABLED"
    else
        warn "  → OS hardening   DISABLED"
    fi

    if [[ "${HARDEN_SSH}" == "true" ]]; then
        echo "    - devsec.hardening.ssh_hardening" >> "${PLAYBOOK}"
        log "  → SSH hardening  ENABLED"
    else
        warn "  → SSH hardening  DISABLED"
    fi

    if [[ "${HARDEN_MYSQL}" == "true" ]]; then
        echo "    - devsec.hardening.mysql_hardening" >> "${PLAYBOOK}"
        log "  → MySQL hardening ENABLED"
    else
        warn "  → MySQL hardening DISABLED"
    fi

    if [[ "${HARDEN_NGINX}" == "true" ]]; then
        echo "    - devsec.hardening.nginx_hardening" >> "${PLAYBOOK}"
        log "  → Nginx hardening ENABLED"
    else
        warn "  → Nginx hardening DISABLED"
    fi

    echo ""
    log "Playbook written to ${PLAYBOOK}"
    echo "──────────────────────────────────────"
    cat "${PLAYBOOK}"
    echo "──────────────────────────────────────"
}

# ── Run the playbook ────────────────────────────────────────────────────────
run_playbook() {
    banner "Executing hardening playbook"

    local extra_args=()

    if [[ "${DRY_RUN}" == "true" ]]; then
        warn "DRY RUN mode — no changes will be made."
        extra_args+=("--check")
    fi

    if [[ "${VERBOSE}" == "true" ]]; then
        extra_args+=("-vvv")
    fi

    # Write a minimal inventory
    local inventory="${WORK_DIR}/inventory"
    echo "localhost ansible_connection=local" > "${inventory}"

    log "Running:  ansible-playbook ${PLAYBOOK} ${extra_args[*]:-}"

    ansible-playbook \
        "${PLAYBOOK}" \
        -i "${inventory}" \
        "${extra_args[@]}" \
        2>&1 | tee -a "${LOGFILE}"

    log "Playbook execution completed."
}

# ── Cleanup ─────────────────────────────────────────────────────────────────
cleanup() {
    banner "Cleanup"
    # Deactivate virtualenv if active
    if command -v deactivate &>/dev/null; then
        deactivate 2>/dev/null || true
    fi
    log "Working directory kept at ${WORK_DIR} for inspection."
    log "Full log saved to ${LOGFILE}"
}

trap cleanup EXIT

# ── Summary before run ──────────────────────────────────────────────────────
summary() {
    banner "Configuration Summary"
    echo "  OS hardening  : ${HARDEN_OS}"
    echo "  SSH hardening : ${HARDEN_SSH}"
    echo "  MySQL harden. : ${HARDEN_MYSQL}"
    echo "  Nginx harden. : ${HARDEN_NGINX}"
    echo "  Dry-run       : ${DRY_RUN}"
    echo "  Verbose       : ${VERBOSE}"
    echo ""

    if [[ "${DRY_RUN}" != "true" ]]; then
        warn "This WILL modify your system configuration!"
        warn "Press Ctrl-C within 5 seconds to abort..."
        sleep 5
    fi
}

# ── Main ────────────────────────────────────────────────────────────────────
main() {
    summary
    install_system_deps
    install_ansible
    install_collection
    build_playbook
    run_playbook

    banner "✅  Hardening Complete"
    log "Review the log at: ${LOGFILE}"
    log "Reboot recommended to fully apply kernel parameters."
}

main "$@"
